# Generated by Django 4.2.16 on 2026-04-25 17:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Resource",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField()),
                ("url", models.URLField(unique=True)),
                (
                    "platform",
                    models.CharField(
                        choices=[
                            ("YouTube", "YouTube"),
                            ("Khan Academy", "Khan Academy"),
                            ("freeCodeCamp", "freeCodeCamp"),
                            ("Harvard CS50", "Harvard CS50"),
                            ("MIT OCW", "MIT OpenCourseWare"),
                            ("fast.ai", "fast.ai"),
                            ("The Odin Project", "The Odin Project"),
                            ("Kaggle", "Kaggle"),
                            ("Google", "Google"),
                            ("AWS", "AWS Skill Builder"),
                            ("Microsoft Learn", "Microsoft Learn"),
                            ("Flutter", "Flutter"),
                            ("Other", "Other"),
                        ],
                        max_length=100,
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("AI_ML", "AI & Machine Learning"),
                            ("WEB_DEV", "Web Development"),
                            ("APP_DEV", "App Development"),
                            ("CLOUD_AWS", "Cloud & AWS"),
                            ("PROGRAMMING", "Programming"),
                            ("DATA_SCIENCE", "Data Science"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "level",
                    models.CharField(
                        choices=[
                            ("BEGINNER", "Beginner"),
                            ("INTERMEDIATE", "Intermediate"),
                            ("ADVANCED", "Advanced"),
                            ("ALL", "All Levels"),
                        ],
                        default="ALL",
                        max_length=20,
                    ),
                ),
                (
                    "resource_type",
                    models.CharField(
                        choices=[
                            ("VIDEO", "Video"),
                            ("COURSE", "Course"),
                            ("ARTICLE", "Article"),
                            ("PLAYLIST", "Playlist"),
                            ("BOOTCAMP", "Bootcamp"),
                        ],
                        max_length=20,
                    ),
                ),
                ("is_free", models.BooleanField(default=True)),
                ("thumbnail_url", models.URLField(blank=True)),
                ("youtube_video_id", models.CharField(blank=True, max_length=50)),
                ("duration", models.CharField(blank=True, max_length=50)),
                ("tags", models.CharField(blank=True, max_length=500)),
                ("view_count", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-view_count", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="CVSkillGap",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("skill_name", models.CharField(max_length=100)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="skill_gaps",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="UserProgress",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("NOT_STARTED", "Not Started"),
                            ("IN_PROGRESS", "In Progress"),
                            ("COMPLETED", "Completed"),
                        ],
                        default="NOT_STARTED",
                        max_length=20,
                    ),
                ),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "resource",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="progress",
                        to="resource_hub.resource",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="progress",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-completed_at"],
                "unique_together": {("user", "resource")},
            },
        ),
        migrations.CreateModel(
            name="Bookmark",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "resource",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bookmarks",
                        to="resource_hub.resource",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bookmarks",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "unique_together": {("user", "resource")},
            },
        ),
    ]
